config/routes.rb
Rails.application.routes.draw do
  
  root 'books#index'

  # Auth routes scope

  devise_for :users 

  # Book routes scope
  
  resources :books, except: [:show] do
    
    # Book notes routes scope

    resources :notes
  
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  # Validations

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :user, presence: true
  
  # Associations 

  belongs_to :user
  has_many :notes
  
end

app/models/note.rb
class Note < ApplicationRecord
    
  # Validations

  validates :name, presence: true, uniqueness: { scope: :book_id }
  validates :book, presence: true
  
  # Associations

  belongs_to :book
  
end

app/models/user.rb
class User < ApplicationRecord

  after_create :set_global

  # (Auth) Devise Modules

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # Validations

  validates :email, presence: true, uniqueness: true

  # Associations

  has_many :books, dependent: :destroy

  private
    def set_global
      self.books.create( name:'Global', global:true )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def record_not_found
    flash[:notice] = "Couldn't find that. Sorry."
    redirect_to books_path
  end
end

app/controllers/books_controller.rb
class BooksController < LayoutController
  
  before_action :get_book, only: [ :edit, :update, :destroy ]

  def index
    @books = current_user.books 
  end
  
  def new
    @book = current_user.books.build
  end

  def create
    @book = current_user.books.build(book_params)

    if @book.save
      redirect_to books_path, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  def edit;end

  def update
    
    if @book.update(book_params)
      redirect_to books_path, notice: 'Book was successfully updated.'
    else
      render :edit
    end

  end

  def destroy
    @book.destroy
    redirect_to books_path, notice: 'Book was successfully destroyed.'
  end

  private
    
  def get_book
    @book = current_user.books.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:name, :global, :user_id)
  end
end

app/controllers/layout_controller.rb
class LayoutController < ApplicationController;end
 

app/controllers/notes_controller.rb
class NotesController < LayoutController

  before_action :set_book
  before_action :get_note, only: [ :show, :edit, :update, :destroy ]
  
  def index
    @notes = @book.notes
  end
  
  def new
    @note = @book.notes.build
  end

  def create
    @note = @book.notes.build(note_params)

    if @note.save
      redirect_to book_notes_path, notice: 'Note was successfully created.'
    else
      render :new
    end
  end

  def show
    @content = Markdown.new(@note.content).to_html.html_safe
  end

  def edit;end

  def update
    
    if @note.update(note_params)
      redirect_to book_notes_path, notice: 'Note was successfully updated.'
    else
      render :edit
    end

  end

  def destroy
    @note.destroy
    redirect_to book_notes_path, notice: 'Note was successfully destroyed.'
  end

  private
    
  def set_book
    @book = current_user.books.find(params[:book_id])
  end
  
  def get_note
    @note = @book.notes.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:name, :content, :book_id)
  end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/books/_book.html.erb
<div class="card m-2">

  <%= link_to(book_notes_path(book), method: :get, class: 'card-background background-book img-fluid') do %>
    <h5 class="card-title p-2"> <span class='text-dark'> <%= book.name %> </span> </h5>
  <% end %>

  <div class="card-footer d-flex justify-content-center p-0">
    <% if not book.global? %>
      <%= link_to(edit_book_path(book), :method => :get) do %>
        <i class="fas fa-pen"></i>
      <% end %>
      <%= link_to book_path(book), method: :delete, data: { confirm: "Are you sure to delete book?" } do %>
        <i class="fas fa-trash"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/books/_form.html.erb
<% if @book.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @book.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with model: @book do |form| %>
  <div class="form-group">
    <%= form.label :name %><br />
    <%= form.text_field :name, autofocus: true, autocomplete: "book name", class:"form-control" %>
  </div>
  <div class="actions m-2">
    <%= form.submit "Confirm",class:"btn btn-primary" %>
  <%= link_to('Cancel', books_url, method: :get, class:"btn btn-secondary") %>                
  </div>
<% end %>

app/views/books/edit.html.erb
<h1><i class="fas fa-book"></i> Edit <%= @book.name %> </h1>

<%= render 'form' %>

app/views/books/index.html.erb
<h2> My Books</h2>
<div class='books-dashboard shadow'>
  <%= link_to(new_book_path, method: :get, class: 'rounded-light-button float-right') do %>
    <i class="fas fa-plus"></i>
    New Book
  <% end %>
  <div class="card-deck">
    <%= render @books %>
  </div>
</div>

app/views/books/new.html.erb
<h1><i class="fas fa-book"></i> New Book</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyNotesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'session', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :section, msg, :id => "flash_#{name}", :class => "alert alert-info flash" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby Notes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% flash.each do | k, msg | %>
      <%= content_tag :div, class: "alert alert-info" do %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= msg %>
      <% end %>
    <% end %>


    <div class="container-fluid main-container">
      <div class="row">
        <div class="p-2 col-sidebar">
          <%= render 'components/sidebar' %>
        </div>
        <div class="col"
          style='max-height: 100vh; overflow-y: auto;'>

          <h1 class='brand'>
            <%= link_to('Ruby Notes',root_url)%>
          </h1>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<% if @note.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @note.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with model: [@book, @note], local: true do |form| %>
  <div class="form-group">
    <%= form.label :name %><br />
    <%= form.text_field :name, autofocus: true, autocomplete: "Note name", class:"form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :content %><br />
    <%= form.text_area :content %>
  </div>
  <div class="actions m-2">
    <%= form.submit "Confirm",class:"btn btn-primary" %>
  <%= link_to('Cancel', book_notes_url(@book), method: :get, class:"btn btn-secondary") %>                
  </div>
<% end %>

<link rel="stylesheet" href="https://unpkg.com/easymde/dist/easymde.min.css">
<script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
<script>
var easyMDE = new EasyMDE({
  element: document.getElementById('note_content'),
  toolbar: ["bold", "italic", "heading","quote","link","ordered-list","unordered-list"],
  status: false
  });
</script>

app/views/notes/_note.html.erb
<div class="card m-2">

  <%= link_to(book_note_path(@book, note), method: :get, class: 'card-background background-note') do %>
    <h5 class="card-title card-title-note"> <span> <%= note.name %> </span> </h5>
  <% end %>
  <div class="card-footer d-flex justify-content-center p-0">
    <%= link_to(edit_book_note_path(@book, note), :method => :get) do %>
      <i class="fas fa-pen"></i>
    <% end %>
    <%= link_to book_note_path(@book, note), method: :delete, data: { confirm: "Are you sure to delete this note?" } do %>
      <i class="fas fa-trash"></i>
    <% end %>
  </div>
</div>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>
<%= render 'form' %>

app/views/notes/index.html.erb
<h2> Notes in <%= @book.name %></h2>
<div class='books-dashboard shadow'>
  <%= link_to(new_book_note_path, method: :get, class: 'rounded-light-button float-right') do %>
    <i class="fas fa-plus"></i>
    New Note
  <% end %>
  <div class="card-deck">
    <%= render @notes %>
    <% if @notes.empty? %>
      <h3 class='p-4 font-weight-light'> This book has no Notes added yet. Add a new one! </h3>
    <% end %>
  </div>
</div>

app/views/notes/new.html.erb
<h1> New Note </h1>
<%= render 'form' %>

app/views/notes/show.html.erb
<h3> <span class='font-weight-bold'> <%= link_to @book.name, book_notes_path(@book) %> </span> / <%= @note.name %>   </h3>
<div class='container-fluid'>
  <div class="row justify-content-center">
    <div class="col-md-6 note-container">
      <div class='note-title'>
        <%= @note.name %>
      </div>
      <%= @content %> 
    </div>
  </div>
  <div class="row justify-content-center">
    <%= link_to(edit_book_note_path(@book, @note), :method => :get) do %>
      <i class="fas fa-pen m-4"></i>
    <% end %>
    <%= link_to book_note_path(@book, @note), method: :delete, data: { confirm: "Are you sure to delete this note?" } do %>
      <i class="fas fa-trash m-4"></i>
    <% end %>
  </div>
</div>